services:

  frontend: 
    image: httpd
    ports:
      - '81:80'
    volumes:
      - ~/my_web_server_files:/usr/local/apache2/htdocs
    depends_on:
      - backend
    networks:
      - front-back
    
      
  backend:
    image: simple_flask
    ports:
      - '82:5000'
    depends_on:
      - database
    networks:
      - front-back
      - back-db
    
  database:
    image: mariadb
    environment: 
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - '83:3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - back-db
      
networks:
  front-back:
  back-db:
  
volumes:
  database:
      
      

 
